### ISSUE TITLE
The project doesn't show up on https://backdropcms.org

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/ajax_markup#2]
The project is not showing up on https://backdropcms.org/project/ajax_markup.

**Comment by docwilmot** [comment]
> The project node could not be created on BackdropCMS.org because no "type" property was specified in the project .info file. Info file contents

https://github.com/backdrop-contrib/ajax_markup/releases/download/1.x-1.0/PACKAGING_ERROR_LOG.txt
