### ISSUE TITLE
Request to overtake maintainership

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/ajax_markup#4]
Per https://github.com/backdrop-contrib/markdowneditor/issues/2 the maintainership of the related _Markdowneditor_ module was passed to me. And since the README file of this module says it's currently seeking maintainers, I'd like to maintain them together.

**Comment by herbdool** [comment]
@alanmels that's okay by me!

**Comment by alanmels** [comment]
@herbdool, I don't have write permissions to the module. It's giving:

> You’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork alanmels/ajax_markup, so you can send a pull request. 

 Could you please take another look at this?

**Comment by stpaultim** [comment]
@alanmels - Just in case you haven't heard yet. The new permissions policy is officially in effect and maintainers of modules should get full admin access over their modules. If you don't have the permissions you need (there is no automatic way to update all of them), just post a request in Zulip or https://github.com/backdrop-ops/contrib.

Maintainers should have (or get) the ability to add new maintainers to their modules.
